### ISSUE TITLE
Another Approach Using normalize

### ISSUE THREAD

**Issue by FlipperPA** [lincolnolivr/remove_accents-pylib#1]
Howdy! I randomly found your package through Bluesky, and wanted to share a different approach we use:

```python
from unicodedata import normalize

def remove_diacritics(text):
    """
    This will remove diacritics such as umlauts and accents from a string. This is
    useful when we need to prepare data for systems such as LDAP.

    Example input: "Carina Müller"
    Example output: "Carina Muller"
    """
    return normalize("NFD", text).encode("ascii", "ignore").decode("utf-8")
```

This might be more complete than the map you're using? Cheers!

**Comment by lincolnolivr** [comment]
Hey FlipperPA!

Thanks a lot for your contribution! I have just added your suggestion to the library. 
Also created the "CONTRIBUTING.md" file to register your name there. 

I'm very new on Github and to be honest, I wasn't expecting to have an interaction so soon haha

I have indeed considered a similar approach and I was looking for something that could not change other types of special strings, for example: 

remove_diacritics('æ') would return ''
remove_diacritics('北亰') would also return ''

But why not having both options? With this change I have also took the opportunity to improve the library readability.

**Comment by FlipperPA** [comment]
Oh awesome, that makes sense! It was good to see someone else tackling this issue, when I came up with this solution, there wasn't much out there. I'd rather have UTF-8 support in LDAP and elsewhere, but some places, it just doesn't exist. :) Great work!
